.\" This file is part of libmail.
.\" 
.\"	(c) 2009 - Dimitris Mandalidis <mandas@users.sourceforge.net>
.\"
.\" libmail is free software: you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation, either version 3 of the License, or
.\" (at your option) any later version.
.\" 
.\" libmail is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\" 
.\" You should have received a copy of the GNU General Public License
.\" along with libmail.  If not, see <http://www.gnu.org/licenses/>.
.TH LIBMAIL_MAILDIR 3 "2009-06-20" "version 0.3" "libmail - A mail handling library"
.SH NAME
maildir_check - Check local maildir for messages
.SH SYNOPSIS
.nf
.B #include <libmail/libmail.h>
.B #include <libmail/maildir.h>
.sp
.BI "int maildir_check(libmail_local_mailbox_t *" "server" ", int *" "n_new_messages" ", int *" "n_messages" );
.fi
.SH DESCRIPTION
It takes a pointer to 
.B libmail_local_mailbox_t 
structure which identify the maildir location. 
.SH "RETURN VALUE"
It returns
.B LIBMAIL_SUCCESS 
on success and 
.B LIBMAIL_SYSERROR
otherwise (errno defined in <errno.h> is set).
.TP
You can retrieve a short description about a specific error through libmail_strerror()
.SH "SEE ALSO"
.BR "maildir" "(5)" "libmail_strerror" "(3)"
.SH "AUTHOR"
Dimitris Mandalidis <mandas AT users DOT sourceforge DOT net>
