.\" This file is part of libmail.
.\" 
.\"	(c) 2009 - Dimitris Mandalidis <mandas@users.sourceforge.net>
.\"
.\" libmail is free software: you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation, either version 3 of the License, or
.\" (at your option) any later version.
.\" 
.\" libmail is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\" 
.\" You should have received a copy of the GNU General Public License
.\" along with libmail.  If not, see <http://www.gnu.org/licenses/>.
.TH POP3_AUTHENTICATE 3 "2009-06-20" "version 0.3" "libmail - A mail handling library"
.SH NAME
pop3_authenticate - Authenticate against a remote POP3 server
.SH SYNOPSIS
.nf
.B #include <libmail/libmail.h>
.B #include <libmail/pop3.h>
.sp
.BI "int pop3_authenticate(pop3_mailbox_t *" "server" );
.SH DESCRIPTION
It 's used to authenticate a user to a remote POP3 mailbox. It takes a pointer to 
.B pop3_mailbox_t 
structure which identify the server's configuration. 
.SH "RETURN VALUE"
Returns
.B LIBMAIL_SUCCESS 
on success. On error it returns :
.TP
.B LIBMAIL_ALREADY_AUTHORIZED
If the uses has been already authenticated against the remote server.
.TP
.B LIBMAIL_SYSERROR
On system error (see errno for details).
.TP
.B LIBMAIL_POP3_INVALID_USERPASS
On invalid credentials used by the LOGIN authentication method.
.TP
.B LIBMAIL_SASL_ERROR
On error which occured during the SASL authentication method procedure.
.TP
.B LIBMAIL_INVALID_AUTH_METHOD
On invalid requested authentication method.
.SH "SEE ALSO"
.B RFC 1939, RFC 2595, RFC 1734
.sp
.BR "libmail_strerror" "(3), " "set_pop3_auth_type" "(3), " "set_pop3_hostname" "(3), " "set_pop3_inet_family" "(3), " "set_pop3_mailbox" "(3), "
.BR "set_pop3_password" "(3), " "set_pop3_port" "(3), " "set_pop3_security_level" "(3), " "set_pop3_username" "(3), " "libmail_init_pop3_mailbox" "(3)."
.SH "AUTHOR"
Dimitris Mandalidis <mandas AT users DOT sourceforge DOT net>
