.\" This file is part of libmail.
.\" 
.\"	(c) 2009 - Dimitris Mandalidis <mandas@users.sourceforge.net>
.\"
.\" libmail is free software: you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation, either version 3 of the License, or
.\" (at your option) any later version.
.\" 
.\" libmail is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\" 
.\" You should have received a copy of the GNU General Public License
.\" along with libmail.  If not, see <http://www.gnu.org/licenses/>.
.TH SET_IMAP4_PASSWORD 3 "2009-06-18" "version 0.3" "libmail - A mail handling library"
.SH NAME
set_imap4_username - Set IMAP4 account username
.SH SYNOPSIS
.nf
.B #include <libmail/libmail.h>
.B #include <libmail/imap4.h>
.sp
.BI "void set_imap4_username(imap4_mailbox_t " "*mailbox" ", const char *" "username" ")"
.sp
.fi
.SH DESCRIPTION
Set the IMAP4 account username.
.SH "SEE ALSO"
.BR "imap4_authenticate" "(3)."
.sp
.B RFC 1730, RFC 2595, RFC 1731
.SH "AUTHOR"
Dimitris Mandalidis <mandas AT users DOT sourceforge DOT net>
